#
# Run all checks on PRs and pushes
#
name: Checks

# Controls when the action will run.
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [main, next, beta, alpha]

  # Run to keep published content and webmentions fresh.
  # Note: GitHub cron schedules run in UTC.
  schedule:
    - cron: '30 10 * * *' # 12:30 CET
    - cron: '30 14 * * *' # 16:30 CET
    - cron: '30 18 * * *' # 20:30 CET

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}_${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-lint:
    name: '▶️ actions'
    uses: ./.github/workflows/pr-lint.yml
    secrets: inherit
    if: github.event_name == 'pull_request'

  dependencies:
    name: '▶️ actions'
    uses: ./.github/workflows/dependencies.yml
    permissions:
      pull-requests: write
      contents: write

  npm-build:
    name: '▶️ actions'
    uses: ./.github/workflows/npm-build.yml
