name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    #name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    #runs-on: ${{ matrix.os }}
    #strategy:
    #  matrix:
    #    node_version: ['8', '10', '12']
    #    os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.4
        with:
          check-latest: true

      - name: Install dependencies
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: '🖼️ Visual test'
        run: npx percy snapshot ./dist
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
