name: Cleanup Cloudflare Deployments

on:
  workflow_dispatch:
    inputs:
      cleanup-types:
        description: 'Type of cleanup to perform'
        required: false
        default: 'preview'
        type: choice
        options:
          - preview
          - production
          - all
      dry-run:
        description: 'Run the workflow in dry-run mode'
        required: false
        default: false
        type: boolean

  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Cloudflare Deployments
        uses: Th3S4mur41/cleanup-cloudflare-deployments@c4113768181fc0fe97becc9aaf84b471dd038d3d # v2.0.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cleanup-types: ${{ github.event.inputs.cleanup-types || 'all' }}
          production-keep: 5
          dry-run: ${{ github.event.inputs.dry-run || false }}
