# This is the workflow to automatically approve and merge dependabot PRs
#
name: Dependencies

on:
  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependency-review:
    name: '⛓️ Dependency Review'
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v4

      - name: '🛡️ Dependency Review'
        uses: actions/dependency-review-action@v3
