# This is the workflow to build and test the code
name: Build & Test

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: '🛠️ Build & Test'
    runs-on: ubuntu-latest

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: '⚙️ Use Node.js'
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'

      - name: '⛓️ Install dependencies'
        env:
          HUSKY: 0
        run: npm ci --no-audit --prefer-offline --progress=false

      - name: '💾 Cache Astro image optimization'
        uses: actions/cache@v5
        with:
          path: .astro
          key: astro-cache-${{ runner.os }}-${{ github.ref_name }}-v1
          restore-keys: |
            astro-cache-${{ runner.os }}-${{ github.ref_name }}-v1
            astro-cache-${{ runner.os }}-main-v1
            astro-cache-${{ runner.os }}-

      - name: '✅ Lint code'
        run: npm run lint -- --reporter=github

      - name: '🛠️ Build'
        env:
          PREVIEW_FUTURE_CONTENT: ${{ github.event_name == 'pull_request' && 'true' || '' }}
        run: npm run build --if-present

      - name: '🧫 Run tests'
        run: npm run test --if-present

      - name: '📎 Upload build output'
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            dist/
            package.json
            package-lock.json
          retention-days: 1
