# This is workflow runs on PR
#
name: Pull Request

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: '▶️ actions'
    uses: ./.github/workflows/dependencies.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN  }}
